CalculatorMVC/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CalculatorMVC.Models
{
    public class CalculatorModel
    {
        [Required]
        public int FirstNumber { get; set;}

        [Required]
        public int SecondNumber { get; set;}
        public int Result { get; set;}
    }
}

CalculatorMVC/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CalculatorMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CalculatorMVC.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult handleAddition(CalculatorModel data, string submitButton) 
        {
            switch (submitButton)
            {
                case "add" :
                    data.Result = data.FirstNumber + data.SecondNumber;
                    return View("Index", data);
                    break;

                case "sub":
                    data.Result = data.FirstNumber - data.SecondNumber;
                    return View("Index", data);
                    break;

                case "div":
                    data.Result = data.FirstNumber / data.SecondNumber;
                    return View("Index", data);
                    break;

                default:
                    data.Result = data.FirstNumber * data.SecondNumber;
                    return View("Index", data);
            }
            
        }

        public IActionResult handleSubstraction(CalculatorModel data) 
        {
            data.Result = data.FirstNumber - data.SecondNumber;
            return View("Index", data);

        }

        public IActionResult handleDivision(CalculatorModel data) 
        {
            data.Result = data.FirstNumber / data.SecondNumber;
            return View("Index", data);
        }

        public IActionResult handleMultiplication(CalculatorModel data)
        {
            data.Result = data.FirstNumber * data.SecondNumber;
            return View("Index", data);
        }
    }
}

CalculatorMVC/Views/Calculator/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CalculatorMVC.Models.CalculatorModel;

<h1 class="text-center text-danger"  >Calculator</h1>


<div class="row" >
    <div class="col-lg-5 mx-auto ">
        <div class="card" >
            <div class="card-body">

                @Html.BeginForm("handleAddition", "Calculator", FormMethod.Post);
                
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstNumber" class="control-label">First Number</label> <br />
                        <input asp-for="FirstNumber" class="form-control" />
                        <span asp-validation-for="FirstNumber" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="SecondNumber" class="control-label">Second Number</label> <br />
                        <input asp-for="SecondNumber" class="form-control" />
                        <span asp-validation-for="SecondNumber" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Result" class="control-label">Result</label>
                        <span>=</span>
                        @Html.DisplayFor(Model => Model.Result)
                    </div>


                    <div class="text-center">
                        <button type="submit" class="btn-primary" name="add" >Addition</button>
                        <button type="submit" class="btn-success" name="sub" >Substraction</button>
                        <button type="submit" class="btn-primary" name="div">Division</button>
                        <button type="submit" class="btn-success" name="multi">Multiplication</button>
                    </div>
                
            </div>
        </div>
    </div>

</div>